### ISSUE TITLE
Roadmap thing

### ISSUE THREAD

**Issue by flashwave** [flashwave/satoko#1]
# Phase 1
- [ ] Multiple boards
- [ ] 4chan-style board layout
  - [ ] CSS switcher
- [ ] Threads
  - [ ] Replying
    - [ ] Deleting
  - [ ] Image/file attaching (multiple at once?)
- [ ] Catalog
- [ ] Archive
- [ ] Quoting
  - [ ] Standard "greentext"
  - [ ] Post linking
  - [ ] Inter-board linking

# Phase 2
- [ ] RSS Feed
- [ ] Modular spambot protection (i.e. recaptcha)
- [ ] Basic moderation
  - [ ] Authentication
    - [ ] Self contained
    - [ ] Remote oauth2 server
  - [ ] Reporting
  - [ ] Banning

# Phase 3
- [ ] Alternative board layouts (i.e. 2ch)
- [ ] Searching
- [ ] Homepage
- [ ] Frames
